# RECOVERY_GAP_LINE_1
# RECOVERY_GAP_LINE_2
# RECOVERY_GAP_LINE_3
# RECOVERY_GAP_LINE_4
# RECOVERY_GAP_LINE_5
# RECOVERY_GAP_LINE_6
# RECOVERY_GAP_LINE_7
# RECOVERY_GAP_LINE_8
# RECOVERY_GAP_LINE_9
# RECOVERY_GAP_LINE_10
# RECOVERY_GAP_LINE_11
# RECOVERY_GAP_LINE_12
# RECOVERY_GAP_LINE_13
# RECOVERY_GAP_LINE_14
# RECOVERY_GAP_LINE_15
# RECOVERY_GAP_LINE_16
# RECOVERY_GAP_LINE_17
# RECOVERY_GAP_LINE_18
# RECOVERY_GAP_LINE_19
# RECOVERY_GAP_LINE_20
# RECOVERY_GAP_LINE_21
# RECOVERY_GAP_LINE_22
# RECOVERY_GAP_LINE_23
# RECOVERY_GAP_LINE_24
# RECOVERY_GAP_LINE_25
# RECOVERY_GAP_LINE_26
# RECOVERY_GAP_LINE_27
# RECOVERY_GAP_LINE_28
# RECOVERY_GAP_LINE_29
# RECOVERY_GAP_LINE_30
# RECOVERY_GAP_LINE_31
# RECOVERY_GAP_LINE_32
# RECOVERY_GAP_LINE_33
# RECOVERY_GAP_LINE_34
# RECOVERY_GAP_LINE_35
# RECOVERY_GAP_LINE_36
# RECOVERY_GAP_LINE_37
# RECOVERY_GAP_LINE_38
# RECOVERY_GAP_LINE_39
# RECOVERY_GAP_LINE_40
# RECOVERY_GAP_LINE_41
# RECOVERY_GAP_LINE_42
# RECOVERY_GAP_LINE_43
# RECOVERY_GAP_LINE_44
# RECOVERY_GAP_LINE_45
# RECOVERY_GAP_LINE_46
# RECOVERY_GAP_LINE_47
# RECOVERY_GAP_LINE_48
# RECOVERY_GAP_LINE_49
# RECOVERY_GAP_LINE_50
# RECOVERY_GAP_LINE_51
# RECOVERY_GAP_LINE_52
# RECOVERY_GAP_LINE_53
# RECOVERY_GAP_LINE_54
# RECOVERY_GAP_LINE_55
# RECOVERY_GAP_LINE_56
# RECOVERY_GAP_LINE_57
# RECOVERY_GAP_LINE_58
# RECOVERY_GAP_LINE_59
# RECOVERY_GAP_LINE_60
# RECOVERY_GAP_LINE_61
# RECOVERY_GAP_LINE_62
# RECOVERY_GAP_LINE_63
# RECOVERY_GAP_LINE_64
# RECOVERY_GAP_LINE_65
# RECOVERY_GAP_LINE_66
# RECOVERY_GAP_LINE_67
# RECOVERY_GAP_LINE_68
# RECOVERY_GAP_LINE_69
# RECOVERY_GAP_LINE_70
# RECOVERY_GAP_LINE_71
# RECOVERY_GAP_LINE_72
# RECOVERY_GAP_LINE_73
# RECOVERY_GAP_LINE_74
# RECOVERY_GAP_LINE_75
# RECOVERY_GAP_LINE_76
# RECOVERY_GAP_LINE_77
# RECOVERY_GAP_LINE_78
# RECOVERY_GAP_LINE_79
# RECOVERY_GAP_LINE_80
# RECOVERY_GAP_LINE_81
# RECOVERY_GAP_LINE_82
# RECOVERY_GAP_LINE_83
# RECOVERY_GAP_LINE_84
# RECOVERY_GAP_LINE_85
# RECOVERY_GAP_LINE_86
# RECOVERY_GAP_LINE_87
# RECOVERY_GAP_LINE_88
# RECOVERY_GAP_LINE_89
# RECOVERY_GAP_LINE_90
# RECOVERY_GAP_LINE_91
# RECOVERY_GAP_LINE_92
# RECOVERY_GAP_LINE_93
# RECOVERY_GAP_LINE_94
# RECOVERY_GAP_LINE_95
# RECOVERY_GAP_LINE_96
# RECOVERY_GAP_LINE_97
# RECOVERY_GAP_LINE_98
# RECOVERY_GAP_LINE_99
# RECOVERY_GAP_LINE_100
# RECOVERY_GAP_LINE_101
# RECOVERY_GAP_LINE_102
# RECOVERY_GAP_LINE_103
# RECOVERY_GAP_LINE_104
# RECOVERY_GAP_LINE_105
# RECOVERY_GAP_LINE_106
# RECOVERY_GAP_LINE_107
# RECOVERY_GAP_LINE_108
# RECOVERY_GAP_LINE_109
# RECOVERY_GAP_LINE_110
# RECOVERY_GAP_LINE_111
# RECOVERY_GAP_LINE_112
# RECOVERY_GAP_LINE_113
# RECOVERY_GAP_LINE_114
# RECOVERY_GAP_LINE_115
# RECOVERY_GAP_LINE_116
# RECOVERY_GAP_LINE_117
# RECOVERY_GAP_LINE_118
# RECOVERY_GAP_LINE_119
# RECOVERY_GAP_LINE_120
# RECOVERY_GAP_LINE_121
# RECOVERY_GAP_LINE_122
# RECOVERY_GAP_LINE_123
# RECOVERY_GAP_LINE_124
# RECOVERY_GAP_LINE_125
# RECOVERY_GAP_LINE_126
# RECOVERY_GAP_LINE_127
# RECOVERY_GAP_LINE_128
# RECOVERY_GAP_LINE_129
# RECOVERY_GAP_LINE_130
# RECOVERY_GAP_LINE_131
# RECOVERY_GAP_LINE_132
# RECOVERY_GAP_LINE_133
# RECOVERY_GAP_LINE_134
# RECOVERY_GAP_LINE_135
# RECOVERY_GAP_LINE_136
# RECOVERY_GAP_LINE_137
# RECOVERY_GAP_LINE_138
# RECOVERY_GAP_LINE_139
# RECOVERY_GAP_LINE_140
# RECOVERY_GAP_LINE_141
# RECOVERY_GAP_LINE_142
# RECOVERY_GAP_LINE_143
# RECOVERY_GAP_LINE_144
# RECOVERY_GAP_LINE_145
# RECOVERY_GAP_LINE_146
# RECOVERY_GAP_LINE_147
# RECOVERY_GAP_LINE_148
# RECOVERY_GAP_LINE_149
# RECOVERY_GAP_LINE_150
# RECOVERY_GAP_LINE_151
# RECOVERY_GAP_LINE_152
# RECOVERY_GAP_LINE_153
# RECOVERY_GAP_LINE_154
# RECOVERY_GAP_LINE_155
# RECOVERY_GAP_LINE_156
# RECOVERY_GAP_LINE_157
# RECOVERY_GAP_LINE_158
# RECOVERY_GAP_LINE_159
# RECOVERY_GAP_LINE_160
# RECOVERY_GAP_LINE_161
# RECOVERY_GAP_LINE_162
# RECOVERY_GAP_LINE_163
# RECOVERY_GAP_LINE_164
# RECOVERY_GAP_LINE_165
# RECOVERY_GAP_LINE_166
# RECOVERY_GAP_LINE_167
# RECOVERY_GAP_LINE_168
# RECOVERY_GAP_LINE_169
# RECOVERY_GAP_LINE_170
# RECOVERY_GAP_LINE_171
# RECOVERY_GAP_LINE_172
# RECOVERY_GAP_LINE_173
# RECOVERY_GAP_LINE_174
# RECOVERY_GAP_LINE_175
# RECOVERY_GAP_LINE_176
# RECOVERY_GAP_LINE_177
# RECOVERY_GAP_LINE_178
# RECOVERY_GAP_LINE_179
# RECOVERY_GAP_LINE_180
# RECOVERY_GAP_LINE_181
# RECOVERY_GAP_LINE_182
# RECOVERY_GAP_LINE_183
# RECOVERY_GAP_LINE_184
# RECOVERY_GAP_LINE_185
# RECOVERY_GAP_LINE_186
# RECOVERY_GAP_LINE_187
# RECOVERY_GAP_LINE_188
# RECOVERY_GAP_LINE_189
# RECOVERY_GAP_LINE_190
# RECOVERY_GAP_LINE_191
# RECOVERY_GAP_LINE_192
# RECOVERY_GAP_LINE_193
# RECOVERY_GAP_LINE_194
# RECOVERY_GAP_LINE_195
# RECOVERY_GAP_LINE_196
# RECOVERY_GAP_LINE_197
# RECOVERY_GAP_LINE_198
# RECOVERY_GAP_LINE_199
# RECOVERY_GAP_LINE_200
# RECOVERY_GAP_LINE_201
# RECOVERY_GAP_LINE_202
# RECOVERY_GAP_LINE_203
# RECOVERY_GAP_LINE_204
# RECOVERY_GAP_LINE_205
# RECOVERY_GAP_LINE_206
# RECOVERY_GAP_LINE_207
# RECOVERY_GAP_LINE_208
# RECOVERY_GAP_LINE_209
# RECOVERY_GAP_LINE_210
# RECOVERY_GAP_LINE_211
# RECOVERY_GAP_LINE_212
# RECOVERY_GAP_LINE_213
# RECOVERY_GAP_LINE_214
# RECOVERY_GAP_LINE_215
# RECOVERY_GAP_LINE_216
# RECOVERY_GAP_LINE_217
# RECOVERY_GAP_LINE_218
# RECOVERY_GAP_LINE_219
# RECOVERY_GAP_LINE_220
# RECOVERY_GAP_LINE_221
# RECOVERY_GAP_LINE_222
# RECOVERY_GAP_LINE_223
# RECOVERY_GAP_LINE_224
# RECOVERY_GAP_LINE_225
# RECOVERY_GAP_LINE_226
# RECOVERY_GAP_LINE_227
# RECOVERY_GAP_LINE_228
# RECOVERY_GAP_LINE_229
# RECOVERY_GAP_LINE_230
# RECOVERY_GAP_LINE_231
# RECOVERY_GAP_LINE_232
# RECOVERY_GAP_LINE_233
# RECOVERY_GAP_LINE_234
# RECOVERY_GAP_LINE_235
# RECOVERY_GAP_LINE_236
# RECOVERY_GAP_LINE_237
# RECOVERY_GAP_LINE_238
# RECOVERY_GAP_LINE_239
# RECOVERY_GAP_LINE_240
# RECOVERY_GAP_LINE_241
# RECOVERY_GAP_LINE_242
# RECOVERY_GAP_LINE_243
# RECOVERY_GAP_LINE_244
# RECOVERY_GAP_LINE_245
# RECOVERY_GAP_LINE_246
# RECOVERY_GAP_LINE_247
# RECOVERY_GAP_LINE_248
# RECOVERY_GAP_LINE_249
# RECOVERY_GAP_LINE_250
# RECOVERY_GAP_LINE_251
# RECOVERY_GAP_LINE_252
# RECOVERY_GAP_LINE_253
# RECOVERY_GAP_LINE_254
# RECOVERY_GAP_LINE_255
# RECOVERY_GAP_LINE_256
# RECOVERY_GAP_LINE_257
# RECOVERY_GAP_LINE_258
# RECOVERY_GAP_LINE_259
# RECOVERY_GAP_LINE_260
# RECOVERY_GAP_LINE_261
# RECOVERY_GAP_LINE_262
# RECOVERY_GAP_LINE_263
# RECOVERY_GAP_LINE_264
# RECOVERY_GAP_LINE_265
# RECOVERY_GAP_LINE_266
# RECOVERY_GAP_LINE_267
# RECOVERY_GAP_LINE_268
# RECOVERY_GAP_LINE_269
# RECOVERY_GAP_LINE_270
# RECOVERY_GAP_LINE_271
# RECOVERY_GAP_LINE_272
# RECOVERY_GAP_LINE_273
# RECOVERY_GAP_LINE_274
# RECOVERY_GAP_LINE_275
# RECOVERY_GAP_LINE_276
# RECOVERY_GAP_LINE_277
# RECOVERY_GAP_LINE_278
# RECOVERY_GAP_LINE_279
# RECOVERY_GAP_LINE_280
# RECOVERY_GAP_LINE_281
# RECOVERY_GAP_LINE_282
# RECOVERY_GAP_LINE_283
# RECOVERY_GAP_LINE_284
# RECOVERY_GAP_LINE_285
# RECOVERY_GAP_LINE_286
# RECOVERY_GAP_LINE_287
# RECOVERY_GAP_LINE_288
# RECOVERY_GAP_LINE_289
# RECOVERY_GAP_LINE_290
# RECOVERY_GAP_LINE_291
# RECOVERY_GAP_LINE_292
# RECOVERY_GAP_LINE_293
# RECOVERY_GAP_LINE_294
# RECOVERY_GAP_LINE_295
# RECOVERY_GAP_LINE_296
# RECOVERY_GAP_LINE_297
# RECOVERY_GAP_LINE_298
# RECOVERY_GAP_LINE_299
# RECOVERY_GAP_LINE_300
# RECOVERY_GAP_LINE_301
# RECOVERY_GAP_LINE_302
# RECOVERY_GAP_LINE_303
# RECOVERY_GAP_LINE_304
# RECOVERY_GAP_LINE_305
# RECOVERY_GAP_LINE_306
# RECOVERY_GAP_LINE_307
# RECOVERY_GAP_LINE_308
# RECOVERY_GAP_LINE_309
# RECOVERY_GAP_LINE_310
# RECOVERY_GAP_LINE_311
# RECOVERY_GAP_LINE_312
# RECOVERY_GAP_LINE_313
# RECOVERY_GAP_LINE_314
# RECOVERY_GAP_LINE_315
# RECOVERY_GAP_LINE_316
# RECOVERY_GAP_LINE_317
# RECOVERY_GAP_LINE_318
# RECOVERY_GAP_LINE_319
# RECOVERY_GAP_LINE_320
# RECOVERY_GAP_LINE_321
# RECOVERY_GAP_LINE_322
# RECOVERY_GAP_LINE_323
# RECOVERY_GAP_LINE_324
# RECOVERY_GAP_LINE_325
# RECOVERY_GAP_LINE_326
# RECOVERY_GAP_LINE_327
# RECOVERY_GAP_LINE_328
# RECOVERY_GAP_LINE_329
# RECOVERY_GAP_LINE_330
# RECOVERY_GAP_LINE_331
# RECOVERY_GAP_LINE_332
# RECOVERY_GAP_LINE_333
# RECOVERY_GAP_LINE_334
# RECOVERY_GAP_LINE_335
# RECOVERY_GAP_LINE_336
# RECOVERY_GAP_LINE_337
# RECOVERY_GAP_LINE_338
# RECOVERY_GAP_LINE_339
# RECOVERY_GAP_LINE_340
# RECOVERY_GAP_LINE_341
# RECOVERY_GAP_LINE_342
# RECOVERY_GAP_LINE_343
# RECOVERY_GAP_LINE_344
# RECOVERY_GAP_LINE_345
# RECOVERY_GAP_LINE_346
# RECOVERY_GAP_LINE_347
# RECOVERY_GAP_LINE_348
# RECOVERY_GAP_LINE_349
# RECOVERY_GAP_LINE_350
# RECOVERY_GAP_LINE_351
# RECOVERY_GAP_LINE_352
# RECOVERY_GAP_LINE_353
# RECOVERY_GAP_LINE_354
# RECOVERY_GAP_LINE_355
# RECOVERY_GAP_LINE_356
# RECOVERY_GAP_LINE_357
# RECOVERY_GAP_LINE_358
# RECOVERY_GAP_LINE_359
# RECOVERY_GAP_LINE_360
# RECOVERY_GAP_LINE_361
# RECOVERY_GAP_LINE_362
# RECOVERY_GAP_LINE_363
# RECOVERY_GAP_LINE_364
# RECOVERY_GAP_LINE_365
# RECOVERY_GAP_LINE_366
# RECOVERY_GAP_LINE_367
# RECOVERY_GAP_LINE_368
# RECOVERY_GAP_LINE_369
# RECOVERY_GAP_LINE_370
# RECOVERY_GAP_LINE_371
# RECOVERY_GAP_LINE_372
# RECOVERY_GAP_LINE_373
# RECOVERY_GAP_LINE_374
# RECOVERY_GAP_LINE_375
# RECOVERY_GAP_LINE_376
# RECOVERY_GAP_LINE_377
# RECOVERY_GAP_LINE_378
# RECOVERY_GAP_LINE_379
# RECOVERY_GAP_LINE_380
# RECOVERY_GAP_LINE_381
# RECOVERY_GAP_LINE_382
# RECOVERY_GAP_LINE_383
# RECOVERY_GAP_LINE_384
# RECOVERY_GAP_LINE_385
# RECOVERY_GAP_LINE_386
# RECOVERY_GAP_LINE_387
# RECOVERY_GAP_LINE_388
# RECOVERY_GAP_LINE_389
# RECOVERY_GAP_LINE_390
# RECOVERY_GAP_LINE_391
# RECOVERY_GAP_LINE_392
# RECOVERY_GAP_LINE_393
# RECOVERY_GAP_LINE_394
# RECOVERY_GAP_LINE_395
# RECOVERY_GAP_LINE_396
# RECOVERY_GAP_LINE_397
# RECOVERY_GAP_LINE_398
# RECOVERY_GAP_LINE_399
# RECOVERY_GAP_LINE_400
# RECOVERY_GAP_LINE_401
# RECOVERY_GAP_LINE_402
# RECOVERY_GAP_LINE_403
# RECOVERY_GAP_LINE_404
# RECOVERY_GAP_LINE_405
# RECOVERY_GAP_LINE_406
# RECOVERY_GAP_LINE_407
# RECOVERY_GAP_LINE_408
# RECOVERY_GAP_LINE_409
# RECOVERY_GAP_LINE_410
# RECOVERY_GAP_LINE_411
# RECOVERY_GAP_LINE_412
# RECOVERY_GAP_LINE_413
# RECOVERY_GAP_LINE_414
# RECOVERY_GAP_LINE_415
# RECOVERY_GAP_LINE_416
# RECOVERY_GAP_LINE_417
# RECOVERY_GAP_LINE_418
# RECOVERY_GAP_LINE_419
# RECOVERY_GAP_LINE_420
# RECOVERY_GAP_LINE_421
# RECOVERY_GAP_LINE_422
# RECOVERY_GAP_LINE_423
# RECOVERY_GAP_LINE_424
# RECOVERY_GAP_LINE_425
# RECOVERY_GAP_LINE_426
# RECOVERY_GAP_LINE_427
# RECOVERY_GAP_LINE_428
# RECOVERY_GAP_LINE_429
# RECOVERY_GAP_LINE_430
# RECOVERY_GAP_LINE_431
# RECOVERY_GAP_LINE_432
# RECOVERY_GAP_LINE_433
# RECOVERY_GAP_LINE_434
# RECOVERY_GAP_LINE_435
# RECOVERY_GAP_LINE_436
# RECOVERY_GAP_LINE_437
# RECOVERY_GAP_LINE_438
# RECOVERY_GAP_LINE_439
# RECOVERY_GAP_LINE_440
# RECOVERY_GAP_LINE_441
# RECOVERY_GAP_LINE_442
# RECOVERY_GAP_LINE_443
# RECOVERY_GAP_LINE_444
# RECOVERY_GAP_LINE_445
# RECOVERY_GAP_LINE_446
# RECOVERY_GAP_LINE_447
# RECOVERY_GAP_LINE_448
# RECOVERY_GAP_LINE_449
# RECOVERY_GAP_LINE_450
# RECOVERY_GAP_LINE_451
# RECOVERY_GAP_LINE_452
# RECOVERY_GAP_LINE_453
# RECOVERY_GAP_LINE_454
# RECOVERY_GAP_LINE_455
# RECOVERY_GAP_LINE_456
# RECOVERY_GAP_LINE_457
# RECOVERY_GAP_LINE_458
# RECOVERY_GAP_LINE_459
# RECOVERY_GAP_LINE_460
# RECOVERY_GAP_LINE_461
# RECOVERY_GAP_LINE_462
# RECOVERY_GAP_LINE_463
# RECOVERY_GAP_LINE_464
# RECOVERY_GAP_LINE_465
# RECOVERY_GAP_LINE_466
# RECOVERY_GAP_LINE_467
# RECOVERY_GAP_LINE_468
# RECOVERY_GAP_LINE_469
# RECOVERY_GAP_LINE_470
# RECOVERY_GAP_LINE_471
# RECOVERY_GAP_LINE_472
# RECOVERY_GAP_LINE_473
# RECOVERY_GAP_LINE_474
# RECOVERY_GAP_LINE_475
# RECOVERY_GAP_LINE_476
# RECOVERY_GAP_LINE_477
# RECOVERY_GAP_LINE_478
# RECOVERY_GAP_LINE_479
# RECOVERY_GAP_LINE_480
# RECOVERY_GAP_LINE_481
# RECOVERY_GAP_LINE_482
# RECOVERY_GAP_LINE_483
# RECOVERY_GAP_LINE_484
# RECOVERY_GAP_LINE_485
# RECOVERY_GAP_LINE_486
# RECOVERY_GAP_LINE_487
                freqtrade backtest metric (e.g. Sharpe ratio) before live use.
                """
                # Suggest grid parameters using the same names that GridConfigV2 expects.
                _ = trial.suggest_float("grid_step_pct", 0.005, 0.05)
                _ = trial.suggest_int("grid_levels", 3, 20)
# RECOVERY_GAP_LINE_493
# RECOVERY_GAP_LINE_494
# RECOVERY_GAP_LINE_495
# RECOVERY_GAP_LINE_496
# RECOVERY_GAP_LINE_497
# RECOVERY_GAP_LINE_498
# RECOVERY_GAP_LINE_499
# RECOVERY_GAP_LINE_500
# RECOVERY_GAP_LINE_501
# RECOVERY_GAP_LINE_502
# RECOVERY_GAP_LINE_503
# RECOVERY_GAP_LINE_504
# RECOVERY_GAP_LINE_505
# RECOVERY_GAP_LINE_506
# RECOVERY_GAP_LINE_507
# RECOVERY_GAP_LINE_508
# RECOVERY_GAP_LINE_509
# RECOVERY_GAP_LINE_510
# RECOVERY_GAP_LINE_511
# RECOVERY_GAP_LINE_512
# RECOVERY_GAP_LINE_513
# RECOVERY_GAP_LINE_514
# RECOVERY_GAP_LINE_515
# RECOVERY_GAP_LINE_516
# RECOVERY_GAP_LINE_517
# RECOVERY_GAP_LINE_518
# RECOVERY_GAP_LINE_519
# RECOVERY_GAP_LINE_520
# RECOVERY_GAP_LINE_521
# RECOVERY_GAP_LINE_522
# RECOVERY_GAP_LINE_523
# RECOVERY_GAP_LINE_524
# RECOVERY_GAP_LINE_525
# RECOVERY_GAP_LINE_526
# RECOVERY_GAP_LINE_527
# RECOVERY_GAP_LINE_528
# RECOVERY_GAP_LINE_529
# RECOVERY_GAP_LINE_530
# RECOVERY_GAP_LINE_531
# RECOVERY_GAP_LINE_532
# RECOVERY_GAP_LINE_533
# RECOVERY_GAP_LINE_534
# RECOVERY_GAP_LINE_535
# RECOVERY_GAP_LINE_536
# RECOVERY_GAP_LINE_537
# RECOVERY_GAP_LINE_538
# RECOVERY_GAP_LINE_539
# RECOVERY_GAP_LINE_540
# RECOVERY_GAP_LINE_541
# RECOVERY_GAP_LINE_542
# RECOVERY_GAP_LINE_543
# RECOVERY_GAP_LINE_544
# RECOVERY_GAP_LINE_545
# RECOVERY_GAP_LINE_546
# RECOVERY_GAP_LINE_547
# RECOVERY_GAP_LINE_548
# RECOVERY_GAP_LINE_549
# RECOVERY_GAP_LINE_550
# RECOVERY_GAP_LINE_551
# RECOVERY_GAP_LINE_552
# RECOVERY_GAP_LINE_553
# RECOVERY_GAP_LINE_554
# RECOVERY_GAP_LINE_555
# RECOVERY_GAP_LINE_556
# RECOVERY_GAP_LINE_557
# RECOVERY_GAP_LINE_558
# RECOVERY_GAP_LINE_559
# RECOVERY_GAP_LINE_560
# RECOVERY_GAP_LINE_561
# RECOVERY_GAP_LINE_562
# RECOVERY_GAP_LINE_563
# RECOVERY_GAP_LINE_564
# RECOVERY_GAP_LINE_565
# RECOVERY_GAP_LINE_566
# RECOVERY_GAP_LINE_567
# RECOVERY_GAP_LINE_568
# RECOVERY_GAP_LINE_569
# RECOVERY_GAP_LINE_570
# RECOVERY_GAP_LINE_571
# RECOVERY_GAP_LINE_572
# RECOVERY_GAP_LINE_573
# RECOVERY_GAP_LINE_574
# RECOVERY_GAP_LINE_575
# RECOVERY_GAP_LINE_576
# RECOVERY_GAP_LINE_577
# RECOVERY_GAP_LINE_578
# RECOVERY_GAP_LINE_579
# RECOVERY_GAP_LINE_580
# RECOVERY_GAP_LINE_581
# RECOVERY_GAP_LINE_582
# RECOVERY_GAP_LINE_583
# RECOVERY_GAP_LINE_584
# RECOVERY_GAP_LINE_585
# RECOVERY_GAP_LINE_586
# RECOVERY_GAP_LINE_587
# RECOVERY_GAP_LINE_588
# RECOVERY_GAP_LINE_589
# RECOVERY_GAP_LINE_590
# RECOVERY_GAP_LINE_591
# RECOVERY_GAP_LINE_592
# RECOVERY_GAP_LINE_593
# RECOVERY_GAP_LINE_594
# RECOVERY_GAP_LINE_595
# RECOVERY_GAP_LINE_596
# RECOVERY_GAP_LINE_597
# RECOVERY_GAP_LINE_598
# RECOVERY_GAP_LINE_599
# RECOVERY_GAP_LINE_600
# RECOVERY_GAP_LINE_601
# RECOVERY_GAP_LINE_602
# RECOVERY_GAP_LINE_603
# RECOVERY_GAP_LINE_604
# RECOVERY_GAP_LINE_605
# RECOVERY_GAP_LINE_606
# RECOVERY_GAP_LINE_607
# RECOVERY_GAP_LINE_608
# RECOVERY_GAP_LINE_609
# RECOVERY_GAP_LINE_610
# RECOVERY_GAP_LINE_611
# RECOVERY_GAP_LINE_612
# RECOVERY_GAP_LINE_613
# RECOVERY_GAP_LINE_614
# RECOVERY_GAP_LINE_615
# RECOVERY_GAP_LINE_616
# RECOVERY_GAP_LINE_617
# RECOVERY_GAP_LINE_618
# RECOVERY_GAP_LINE_619
# RECOVERY_GAP_LINE_620
# RECOVERY_GAP_LINE_621
# RECOVERY_GAP_LINE_622
# RECOVERY_GAP_LINE_623
# RECOVERY_GAP_LINE_624
# RECOVERY_GAP_LINE_625
# RECOVERY_GAP_LINE_626
# RECOVERY_GAP_LINE_627
# RECOVERY_GAP_LINE_628
# RECOVERY_GAP_LINE_629
# RECOVERY_GAP_LINE_630
# RECOVERY_GAP_LINE_631
# RECOVERY_GAP_LINE_632
# RECOVERY_GAP_LINE_633
# RECOVERY_GAP_LINE_634
# RECOVERY_GAP_LINE_635
# RECOVERY_GAP_LINE_636
# RECOVERY_GAP_LINE_637
# RECOVERY_GAP_LINE_638
# RECOVERY_GAP_LINE_639
# RECOVERY_GAP_LINE_640
# RECOVERY_GAP_LINE_641
# RECOVERY_GAP_LINE_642
# RECOVERY_GAP_LINE_643
# RECOVERY_GAP_LINE_644
# RECOVERY_GAP_LINE_645
# RECOVERY_GAP_LINE_646
# RECOVERY_GAP_LINE_647
# RECOVERY_GAP_LINE_648
# RECOVERY_GAP_LINE_649
# RECOVERY_GAP_LINE_650
# RECOVERY_GAP_LINE_651
# RECOVERY_GAP_LINE_652
# RECOVERY_GAP_LINE_653
# RECOVERY_GAP_LINE_654
# RECOVERY_GAP_LINE_655
# RECOVERY_GAP_LINE_656
# RECOVERY_GAP_LINE_657
# RECOVERY_GAP_LINE_658
# RECOVERY_GAP_LINE_659
# RECOVERY_GAP_LINE_660
# RECOVERY_GAP_LINE_661
# RECOVERY_GAP_LINE_662
# RECOVERY_GAP_LINE_663
# RECOVERY_GAP_LINE_664
# RECOVERY_GAP_LINE_665
# RECOVERY_GAP_LINE_666
# RECOVERY_GAP_LINE_667
# RECOVERY_GAP_LINE_668
# RECOVERY_GAP_LINE_669
# RECOVERY_GAP_LINE_670
# RECOVERY_GAP_LINE_671
# RECOVERY_GAP_LINE_672
# RECOVERY_GAP_LINE_673
# RECOVERY_GAP_LINE_674
# RECOVERY_GAP_LINE_675
# RECOVERY_GAP_LINE_676
# RECOVERY_GAP_LINE_677
# RECOVERY_GAP_LINE_678
# RECOVERY_GAP_LINE_679
# RECOVERY_GAP_LINE_680
# RECOVERY_GAP_LINE_681
# RECOVERY_GAP_LINE_682
# RECOVERY_GAP_LINE_683
# RECOVERY_GAP_LINE_684
# RECOVERY_GAP_LINE_685
# RECOVERY_GAP_LINE_686
# RECOVERY_GAP_LINE_687
# RECOVERY_GAP_LINE_688
# RECOVERY_GAP_LINE_689
# RECOVERY_GAP_LINE_690
# RECOVERY_GAP_LINE_691
# RECOVERY_GAP_LINE_692
# RECOVERY_GAP_LINE_693
# RECOVERY_GAP_LINE_694
# RECOVERY_GAP_LINE_695
# RECOVERY_GAP_LINE_696
# RECOVERY_GAP_LINE_697
# RECOVERY_GAP_LINE_698
# RECOVERY_GAP_LINE_699
# RECOVERY_GAP_LINE_700
# RECOVERY_GAP_LINE_701
# RECOVERY_GAP_LINE_702
# RECOVERY_GAP_LINE_703
# RECOVERY_GAP_LINE_704
# RECOVERY_GAP_LINE_705
# RECOVERY_GAP_LINE_706
# RECOVERY_GAP_LINE_707
# RECOVERY_GAP_LINE_708
# RECOVERY_GAP_LINE_709
# RECOVERY_GAP_LINE_710
# RECOVERY_GAP_LINE_711
# RECOVERY_GAP_LINE_712
# RECOVERY_GAP_LINE_713
# RECOVERY_GAP_LINE_714
# RECOVERY_GAP_LINE_715
# RECOVERY_GAP_LINE_716
# RECOVERY_GAP_LINE_717
# RECOVERY_GAP_LINE_718
# RECOVERY_GAP_LINE_719
# RECOVERY_GAP_LINE_720
# RECOVERY_GAP_LINE_721
# RECOVERY_GAP_LINE_722
# RECOVERY_GAP_LINE_723
# RECOVERY_GAP_LINE_724
# RECOVERY_GAP_LINE_725
# RECOVERY_GAP_LINE_726
# RECOVERY_GAP_LINE_727
# RECOVERY_GAP_LINE_728
# RECOVERY_GAP_LINE_729
# RECOVERY_GAP_LINE_730
# RECOVERY_GAP_LINE_731
# RECOVERY_GAP_LINE_732
# RECOVERY_GAP_LINE_733
# RECOVERY_GAP_LINE_734
# RECOVERY_GAP_LINE_735
# RECOVERY_GAP_LINE_736
# RECOVERY_GAP_LINE_737
# RECOVERY_GAP_LINE_738
# RECOVERY_GAP_LINE_739
# RECOVERY_GAP_LINE_740
# RECOVERY_GAP_LINE_741
# RECOVERY_GAP_LINE_742
# RECOVERY_GAP_LINE_743
# RECOVERY_GAP_LINE_744
# RECOVERY_GAP_LINE_745
# RECOVERY_GAP_LINE_746
# RECOVERY_GAP_LINE_747
# RECOVERY_GAP_LINE_748
# RECOVERY_GAP_LINE_749
# RECOVERY_GAP_LINE_750
# RECOVERY_GAP_LINE_751
# RECOVERY_GAP_LINE_752
# RECOVERY_GAP_LINE_753
# RECOVERY_GAP_LINE_754
# RECOVERY_GAP_LINE_755
# RECOVERY_GAP_LINE_756
# RECOVERY_GAP_LINE_757
# RECOVERY_GAP_LINE_758
# RECOVERY_GAP_LINE_759
# RECOVERY_GAP_LINE_760
# RECOVERY_GAP_LINE_761
# RECOVERY_GAP_LINE_762
# RECOVERY_GAP_LINE_763
# RECOVERY_GAP_LINE_764
# RECOVERY_GAP_LINE_765
# RECOVERY_GAP_LINE_766
# RECOVERY_GAP_LINE_767
# RECOVERY_GAP_LINE_768
# RECOVERY_GAP_LINE_769
# RECOVERY_GAP_LINE_770
# RECOVERY_GAP_LINE_771
# RECOVERY_GAP_LINE_772
# RECOVERY_GAP_LINE_773
# RECOVERY_GAP_LINE_774
# RECOVERY_GAP_LINE_775
# RECOVERY_GAP_LINE_776
# RECOVERY_GAP_LINE_777
# RECOVERY_GAP_LINE_778
# RECOVERY_GAP_LINE_779
# RECOVERY_GAP_LINE_780
# RECOVERY_GAP_LINE_781
# RECOVERY_GAP_LINE_782
# RECOVERY_GAP_LINE_783
# RECOVERY_GAP_LINE_784
# RECOVERY_GAP_LINE_785
# RECOVERY_GAP_LINE_786
# RECOVERY_GAP_LINE_787
# RECOVERY_GAP_LINE_788
# RECOVERY_GAP_LINE_789
# RECOVERY_GAP_LINE_790
# RECOVERY_GAP_LINE_791
# RECOVERY_GAP_LINE_792
# RECOVERY_GAP_LINE_793
# RECOVERY_GAP_LINE_794
# RECOVERY_GAP_LINE_795
# RECOVERY_GAP_LINE_796
# RECOVERY_GAP_LINE_797
# RECOVERY_GAP_LINE_798
# RECOVERY_GAP_LINE_799
# RECOVERY_GAP_LINE_800
# RECOVERY_GAP_LINE_801
# RECOVERY_GAP_LINE_802
# RECOVERY_GAP_LINE_803
# RECOVERY_GAP_LINE_804
# RECOVERY_GAP_LINE_805
# RECOVERY_GAP_LINE_806
# RECOVERY_GAP_LINE_807
# RECOVERY_GAP_LINE_808
# RECOVERY_GAP_LINE_809
# RECOVERY_GAP_LINE_810
# RECOVERY_GAP_LINE_811
# RECOVERY_GAP_LINE_812
# RECOVERY_GAP_LINE_813
# RECOVERY_GAP_LINE_814
# RECOVERY_GAP_LINE_815
# RECOVERY_GAP_LINE_816
# RECOVERY_GAP_LINE_817
# RECOVERY_GAP_LINE_818
# RECOVERY_GAP_LINE_819
# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="morning_run",
        description=(
            "LATS morning workflow CLI 
 scan stocks & crypto, "
            "run optimisers, inject into SharedState."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # ---- global flags ----
    parser.add_argument(
        "--config",
        metavar="PATH",
        default=_DEFAULT_CONFIG_PATH,
        help=f"Path to JSON config file (default: {_DEFAULT_CONFIG_PATH})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Print what would be done without writing to disk or calling APIs",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        default=False,
        help="Enable DEBUG logging",
    )

    subparsers = parser.add_subparsers(dest="subcommand", metavar="SUBCOMMAND")
    subparsers.required = True

    # ------------------------------------------------------------------ #
    # scan-stocks
    # ------------------------------------------------------------------ #
    p_stocks = subparsers.add_parser(
        "scan-stocks",
        help="Run EODHD stock screener and print top-N ranked stocks",
    )
    p_stocks.add_argument(
        "--top-n",
        type=int,
        default=None,
        metavar="INT",
        help="Number of top stocks to display (overrides config, default 20)",
    )
    p_stocks.add_argument(
        "--symbols-file",
        default=None,
        metavar="PATH",
        help="Path to SEC/EODHD symbols JSON file (overrides config, default symbols.json)",
    )
    p_stocks.add_argument(
        "--eodhd-key-env",
        default=None,
        metavar="STR",
        help="Name of env var holding the EODHD API key (default EODHD_API_KEY)",
    )
    p_stocks.add_argument(
        "--weights-db-path",
        default=None,
        metavar="PATH",
        help=(
            "Path to the Optuna SQLite DB containing screener weight studies. "
            "When provided and the DB exists, the best Bayesian scoring weights "
            "are loaded into the screener before scanning (default: none)."
        ),
    )

    # ------------------------------------------------------------------ #
    # scan-crypto
    # ------------------------------------------------------------------ #
    p_crypto = subparsers.add_parser(
        "scan-crypto",
        help="Run CoinGecko crypto screener and print top-N ranked crypto pairs",
    )
    p_crypto.add_argument(
        "--top-n",
        type=int,
        default=None,
        metavar="INT",
        help="Number of top crypto coins to display (overrides config, default 20)",
    )
    p_crypto.add_argument(
        "--coingecko-key-env",
        default=None,
        metavar="STR",
        help=(
            "Name of env var holding the CoinGecko Pro API key "
            "(default COINGECKO_API_KEY; free tier used if key is absent)"
        ),

    # ------------------------------------------------------------------ #
    # optimize-grid
    # ------------------------------------------------------------------ #
    p_grid = subparsers.add_parser(
        "optimize-grid",
        help="Run Optuna grid optimiser for given pairs and write results to SQLite DB",
    )
    p_grid.add_argument(
        "--pairs",
        nargs="+",
        default=None,
        metavar="PAIR",
        help="Pairs to optimise, e.g. BTC/USDT ETH/USDT (overrides config)",
    )
    p_grid.add_argument(
        "--n-trials",
        type=int,
        default=None,
        metavar="INT",
        help="Number of Optuna trials per symbol (default 50)",
    )
    p_grid.add_argument(
        "--db-path",
        default=None,
        metavar="PATH",
        help="Path to Optuna SQLite DB for grid studies (default .cache/optuna_grid.db)",
    )
    p_grid.add_argument(
        "--date-from",
        default=None,
        metavar="YYYY-MM-DD",
        help="Start of backtest window (default 1 year ago)",
    )
    p_grid.add_argument(
        "--date-to",
        default=None,
        metavar="YYYY-MM-DD",
        help="End of backtest window (default today)",
    )
    p_grid.add_argument(
        "--allow-placeholder",
        action="store_true",
        default=False,
        help=(
            "Explicitly enable the stub random objective for testing only. "
            "NEVER use this flag for live trading 
 results will be random noise."
        ),
    )

    # ------------------------------------------------------------------ #
    # optimize-weights
    # ------------------------------------------------------------------ #
    p_weights = subparsers.add_parser(
        "optimize-weights",
        help="Run Bayesian screener weights optimiser for StockScreenerModule",
    )
    p_weights.add_argument(
        "--symbols",
        nargs="+",
        default=None,
        metavar="STR",
        help="Ticker symbols to include in the backtest universe (overrides config)",
    )
    p_weights.add_argument(
        "--n-trials",
        type=int,
        default=None,
        metavar="INT",
        help="Number of Optuna trials (default 50)",
    )
    p_weights.add_argument(
        "--db-path",
        default=None,
        metavar="PATH",
        help="Path to Optuna SQLite DB for weight studies (default .cache/screener_weights.db)",
    )
    p_weights.add_argument(
        "--date-from",
        metavar="YYYY-MM-DD",
        help="Start of backtest window (default 1 year ago)",
    )
    p_weights.add_argument(
        "--date-to",
        default=None,
        metavar="YYYY-MM-DD",
        help="End of backtest window (default today)",
    )

    # ------------------------------------------------------------------ #
    # morning (full workflow)
    # ------------------------------------------------------------------ #
    subparsers.add_parser(
        "morning",
        help=(
            "Run the full morning workflow: scan-stocks, scan-crypto, "
            "optimize-grid, optimize-weights, then inject into SharedState"
        ),
    )

    return parser


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def _dispatch(args: argparse.Namespace, cfg: Dict[str, Any]) -> int:
    """Route parsed args to the right subcommand function.

    Returns
    -------
    int
        Exit code (0 = success, 1 = error).
    """
    try:
        if args.subcommand == "scan-stocks":
            cmd_scan_stocks(args, cfg)
        elif args.subcommand == "scan-crypto":
            cmd_scan_crypto(args, cfg)
        elif args.subcommand == "optimize-grid":
            cmd_optimize_grid(args, cfg)
        elif args.subcommand == "optimize-weights":
            cmd_optimize_weights(args, cfg)
        elif args.subcommand == "morning":
            cmd_morning(args, cfg)
        else:
            log.error("Unknown subcommand: %s", args.subcommand)
            return 1
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)
        return 130
    except Exception as exc:  # noqa: BLE001
        log.exception("Unexpected error in subcommand %r: %s", args.subcommand, exc)
        return 1
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: Optional[List[str]] = None) -> int:
    """Parse arguments, load config, and dispatch to the appropriate handler.

    Parameters
    ----------
    argv:
        Argument list (defaults to ``sys.argv[1:]`` when ``None``).

    Returns
    -------
    int
        Exit code suitable for :func:`sys.exit`.
    """
    parser = _build_parser()
    args = parser.parse_args(argv)

    _configure_logging(verbose=args.verbose)

    log.debug("morning_run starting with args: %s", args)

    cfg = _load_config(args.config)

    return _dispatch(args, cfg)


if __name__ == "__main__":
# RECOVERY_GAP_LINE_1091
# RECOVERY_GAP_LINE_1092